[versions]
commonmark = "0.13.0"       # $commonMarkVersion
dagger = "2.56.2"           # $daggerVersion
coil = "2.7.0"              # $coilVersion
junit = "4.13.2"
robolectric = "4.14.1"
mockito = "5.18.0"
okhttp = "4.12.0"
picasso = "2.71828"
glide = "4.16.0"
androidsvg = "1.4"
androidgif15 = "1.2.29"
androidgif20 = "1.2.29"
jlatexmath = "0.2.0"
prism4j = "2.0.0"
debug = "5.1.0"
adapt = "5.0.0"
ixjava = "1.0.0"
gson = "2.13.1"
commonsio = "2.19.0"

[libraries]
x-annotations = { module = "androidx.annotation:annotation", version = "1.9.1" }
x-recyclerview = { module = "androidx.recyclerview:recyclerview", version = "1.4.0" }
x-core = { module = "androidx.core:core", version = "1.16.0" }
x-appcompat = { module = "androidx.appcompat:appcompat", version = "1.7.1" }
x-cardview = { module = "androidx.cardview:cardview", version = "1.0.0" }
x-fragment = { module = "androidx.fragment:fragment", version = "1.8.8" }

commonmark = { module = "com.atlassian.commonmark:commonmark", version.ref = "commonmark" }
commonmark-strikethrough = { module = "com.atlassian.commonmark:commonmark-ext-gfm-strikethrough", version.ref = "commonmark" }
commonmark-table = { module = "com.atlassian.commonmark:commonmark-ext-gfm-tables", version.ref = "commonmark" }

android-svg = { module = "com.caverock:androidsvg", version.ref = "androidsvg" }
android-gif = { module = "pl.droidsonroids.gif:android-gif-drawable", version.ref = "androidgif15" }
android-gif-impl = { module = "pl.droidsonroids.gif:android-gif-drawable", version.ref = "androidgif20" }

jlatexmath-android = { module = "ru.noties:jlatexmath-android", version.ref = "jlatexmath" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
prism4j = { module = "io.noties:prism4j", version.ref = "prism4j" }
debug = { module = "io.noties:debug", version.ref = "debug" }
adapt = { module = "io.noties:adapt", version.ref = "adapt" }
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
picasso = { module = "com.squareup.picasso:picasso", version.ref = "picasso" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
coil = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-base = { module = "io.coil-kt:coil-base", version.ref = "coil" }
ix-java = { module = "com.github.akarnokd:ixjava", version.ref = "ixjava" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
commons-io = { module = "commons-io:commons-io", version.ref = "commonsio" }

#annotation-processor
prism4j-bundler = { module = "io.noties:prism4j-bundler", version.ref = "prism4j" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }

#test
junit = { module = "junit:junit", version.ref = "junit" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito" }
commonmark-test-util = { module = "org.commonmark:commonmark-test-util", version = "0.24.0" }
